Import the Libraries

In [1]:
import pandas as pd
import numpy as np
import glob

Create an Empty DataFrame

In [2]:
all_data=pd.DataFrame()

Loop through all the 104 files matching the pattern and load the excel file into the DataFrame and then appending the contents to the DataFrame created above

In [5]:
for f in glob.glob("datasets/datasets/weekly_call_data/weekdata_*.xlsx"):
    df=pd.read_excel(f)
    print(f)
    all_data=all_data.append(df, ignore_index=True)

datasets/datasets/weekly_call_data\weekdata_000.xlsx
datasets/datasets/weekly_call_data\weekdata_001.xlsx
datasets/datasets/weekly_call_data\weekdata_002.xlsx
datasets/datasets/weekly_call_data\weekdata_003.xlsx
datasets/datasets/weekly_call_data\weekdata_004.xlsx
datasets/datasets/weekly_call_data\weekdata_005.xlsx
datasets/datasets/weekly_call_data\weekdata_006.xlsx
datasets/datasets/weekly_call_data\weekdata_007.xlsx
datasets/datasets/weekly_call_data\weekdata_008.xlsx
datasets/datasets/weekly_call_data\weekdata_009.xlsx
datasets/datasets/weekly_call_data\weekdata_010.xlsx
datasets/datasets/weekly_call_data\weekdata_011.xlsx
datasets/datasets/weekly_call_data\weekdata_012.xlsx
datasets/datasets/weekly_call_data\weekdata_013.xlsx
datasets/datasets/weekly_call_data\weekdata_014.xlsx
datasets/datasets/weekly_call_data\weekdata_015.xlsx
datasets/datasets/weekly_call_data\weekdata_016.xlsx
datasets/datasets/weekly_call_data\weekdata_017.xlsx
datasets/datasets/weekly_call_data\weekdata_018.xlsx
datasets/datasets/weekly_call_data\weekdata_019.xlsx
datasets/datasets/weekly_call_data\weekdata_020.xlsx
datasets/datasets/weekly_call_data\weekdata_021.xlsx
datasets/datasets/weekly_call_data\weekdata_022.xlsx
datasets/datasets/weekly_call_data\weekdata_023.xlsx
datasets/datasets/weekly_call_data\weekdata_024.xlsx
datasets/datasets/weekly_call_data\weekdata_025.xlsx
datasets/datasets/weekly_call_data\weekdata_026.xlsx
datasets/datasets/weekly_call_data\weekdata_027.xlsx
datasets/datasets/weekly_call_data\weekdata_028.xlsx
datasets/datasets/weekly_call_data\weekdata_029.xlsx
datasets/datasets/weekly_call_data\weekdata_030.xlsx
datasets/datasets/weekly_call_data\weekdata_031.xlsx
datasets/datasets/weekly_call_data\weekdata_032.xlsx
datasets/datasets/weekly_call_data\weekdata_033.xlsx
datasets/datasets/weekly_call_data\weekdata_034.xlsx
datasets/datasets/weekly_call_data\weekdata_035.xlsx
datasets/datasets/weekly_call_data\weekdata_036.xlsx
datasets/datasets/weekly_call_data\weekdata_037.xlsx
datasets/datasets/weekly_call_data\weekdata_038.xlsx
datasets/datasets/weekly_call_data\weekdata_039.xlsx
datasets/datasets/weekly_call_data\weekdata_040.xlsx
datasets/datasets/weekly_call_data\weekdata_041.xlsx
datasets/datasets/weekly_call_data\weekdata_042.xlsx
datasets/datasets/weekly_call_data\weekdata_043.xlsx
datasets/datasets/weekly_call_data\weekdata_044.xlsx
datasets/datasets/weekly_call_data\weekdata_045.xlsx
datasets/datasets/weekly_call_data\weekdata_046.xlsx
datasets/datasets/weekly_call_data\weekdata_047.xlsx
datasets/datasets/weekly_call_data\weekdata_048.xlsx
datasets/datasets/weekly_call_data\weekdata_049.xlsx
datasets/datasets/weekly_call_data\weekdata_050.xlsx
datasets/datasets/weekly_call_data\weekdata_051.xlsx
datasets/datasets/weekly_call_data\weekdata_052.xlsx
datasets/datasets/weekly_call_data\weekdata_053.xlsx
datasets/datasets/weekly_call_data\weekdata_054.xlsx
datasets/datasets/weekly_call_data\weekdata_055.xlsx
datasets/datasets/weekly_call_data\weekdata_056.xlsx
datasets/datasets/weekly_call_data\weekdata_057.xlsx
datasets/datasets/weekly_call_data\weekdata_058.xlsx
datasets/datasets/weekly_call_data\weekdata_059.xlsx
datasets/datasets/weekly_call_data\weekdata_060.xlsx
datasets/datasets/weekly_call_data\weekdata_061.xlsx
datasets/datasets/weekly_call_data\weekdata_062.xlsx
datasets/datasets/weekly_call_data\weekdata_063.xlsx
datasets/datasets/weekly_call_data\weekdata_064.xlsx
datasets/datasets/weekly_call_data\weekdata_065.xlsx
datasets/datasets/weekly_call_data\weekdata_066.xlsx
datasets/datasets/weekly_call_data\weekdata_067.xlsx
datasets/datasets/weekly_call_data\weekdata_068.xlsx
datasets/datasets/weekly_call_data\weekdata_069.xlsx
datasets/datasets/weekly_call_data\weekdata_070.xlsx
datasets/datasets/weekly_call_data\weekdata_071.xlsx
datasets/datasets/weekly_call_data\weekdata_072.xlsx
datasets/datasets/weekly_call_data\weekdata_073.xlsx
datasets/datasets/weekly_call_data\weekdata_074.xlsx
datasets/datasets/weekly_call_data\weekdata_075.xlsx
datasets/datasets/weekly_call_data\weekdata_076.xlsx
datasets/datasets/weekly_call_data\weekdata_077.xlsx
datasets/datasets/weekly_call_data\weekdata_078.xlsx
datasets/datasets/weekly_call_data\weekdata_079.xlsx
datasets/datasets/weekly_call_data\weekdata_080.xlsx
datasets/datasets/weekly_call_data\weekdata_081.xlsx
datasets/datasets/weekly_call_data\weekdata_082.xlsx
datasets/datasets/weekly_call_data\weekdata_083.xlsx
datasets/datasets/weekly_call_data\weekdata_084.xlsx
datasets/datasets/weekly_call_data\weekdata_085.xlsx
datasets/datasets/weekly_call_data\weekdata_086.xlsx
datasets/datasets/weekly_call_data\weekdata_087.xlsx
datasets/datasets/weekly_call_data\weekdata_088.xlsx
datasets/datasets/weekly_call_data\weekdata_089.xlsx
datasets/datasets/weekly_call_data\weekdata_090.xlsx
datasets/datasets/weekly_call_data\weekdata_091.xlsx
datasets/datasets/weekly_call_data\weekdata_092.xlsx
datasets/datasets/weekly_call_data\weekdata_093.xlsx
datasets/datasets/weekly_call_data\weekdata_094.xlsx
datasets/datasets/weekly_call_data\weekdata_095.xlsx
datasets/datasets/weekly_call_data\weekdata_096.xlsx
datasets/datasets/weekly_call_data\weekdata_097.xlsx
datasets/datasets/weekly_call_data\weekdata_098.xlsx
datasets/datasets/weekly_call_data\weekdata_099.xlsx
datasets/datasets/weekly_call_data\weekdata_100.xlsx
datasets/datasets/weekly_call_data\weekdata_101.xlsx
datasets/datasets/weekly_call_data\weekdata_102.xlsx
datasets/datasets/weekly_call_data\weekdata_103.xlsx

Display the first 6 rows of the final DataFrame

In [6]:
all_data.head(6)

,Unnamed: 0,CallingNumber,DayOfWeek,TimeOfDay,CallDuration,ReasonForCall,AnsweringAgent
0,0,774-823-8593,thu,10:30,20,Product Inquiry,Cameron
1,1,432-403-9821,fri,11:24,10,Complaint,Cameron
2,2,274-683-6814,tue,15:43,17,Technical Support,Kennedy
3,3,681-402-6913,tue,13:44,2,Technical Support,Lisa
4,4,242-336-6459,wed,10:50,19,Technical Support,Kennedy
5,5,689-467-7418,tue,15:54,4,Product Inquiry,Lisa

Display the Statistics of Data

In [7]:
all_data.describe()

          Unnamed: 0   CallDuration
count  379374.000000  379374.000000
mean      690.307963      12.516967
std       459.003272       6.925807
min         0.000000       1.000000
25%       311.000000       7.000000
50%       624.000000      13.000000
75%      1013.000000      19.000000
max      1944.000000      24.000000